# SPDX-FileCopyrightText: 2024 Eli Array Minkoff
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Eli Array Minkoff's Tech Journal"
SPDX-PackageSupplier = "Eli Array Minkoff <eli@planetminkoff.com>"
SPDX-PackageDownloadLocation = "https://tech-docs.earrayminkoff.tech"
annotations = []
